### ISSUE TITLE
Floor plan image URL invalid

### ISSUE THREAD

**Issue by RobinCaroff** [GDG-Nantes/DevfestNantesMobile#146]
Floor plan image URL changed in the GDG-Nantes/Devfest2023 repo.

We need to fix it in the Confeti's import script.

**Comment by martinbonnin** [comment]
Feel free to open a PR. Or I can do it too if you know the new url.

**Comment by RobinCaroff** [comment]
@martinbonnin done : https://github.com/joreilly/Confetti/pull/877

**Comment by RobinCaroff** [comment]
@martinbonnin sorry the PR was wrong. Here's the new one :
https://github.com/joreilly/Confetti/pull/878

**Comment by RobinCaroff** [comment]
Fixed with https://github.com/joreilly/Confetti/pull/878 🎉
