### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by RobinCaroff** [GDG-Nantes/DevfestNantesMobile#21]
We should setup an analytics solution.

@SRihet I suggest that you write the analytics protocol and models in the shared module and that we document the tagging plan in the repo's wiki.
 Once we agree on the tagging plan we proceed to Android and iOS implementations.

**Comment by SRihet** [comment]
Ok @RobinCaroff , I started the events documentation  in the wiki

**Comment by RobinCaroff** [comment]
Resolved with #77
