### ISSUE TITLE
Apollo's SQLite cache not compiling on iOS

### ISSUE THREAD

**Issue by RobinCaroff** [GDG-Nantes/DevfestNantesMobile#24]
The iOS app does not compile when using Apollo's [SQLite cache](https://www.apollographql.com/docs/kotlin/caching/normalized-cache#sqlite-cache).

![image](https://user-images.githubusercontent.com/10415655/190015947-203a9fa4-c114-4f40-9a58-a19293deccb7.png)

For now we only use the [In-memory cache](https://www.apollographql.com/docs/kotlin/caching/normalized-cache#in-memory-cache) on iOS but we should chain both in-memory and SQLite caches like on Android.

**Comment by martinbonnin** [comment]
You will need to link the final Android app with `sqlite3`:

<img width="335" alt="Screenshot 2022-09-14 at 10 48 30" src="https://user-images.githubusercontent.com/3974977/190107587-ac7ee586-7ddd-4779-a4da-6783c1217f9c.png">

I would have expected the link flags to be inherited from the framework, not sure why it's not the case. I'll dig

**Comment by martinbonnin** [comment]
Turns out that frameworks cannot propagate their linker flags so it can't be done through frameworks. Maybe there's a cocoapods option somewhere
