### ISSUE TITLE
Wrong duration for some talks

### ISSUE THREAD

**Issue by sadstag** [GDG-Nantes/DevfestNantesMobile#85]
Hi,

In Android App, for October 20th, talks beginning at 11:10 have duration announced duration of 170 minutes, which seems incorrect.

**Comment by martinbonnin** [comment]
Thanks for the bug report 🙏  I'll look into it

**Comment by martinbonnin** [comment]
Turns out this is a side effect of https://github.com/GDG-Nantes/DevfestNantesMobile/issues/83.
Since the website data doesn't indicate and end time, we're using the start time of the next session in a given room to compute the endtime, which broken when removing the rooms...

**Comment by RobinCaroff** [comment]
@martinbonnin it seems that the fix broke something. I cannot fetch sessions data anymore. I get the following error message : `Exception while fetching data (/sessions) : No such property name`

**Comment by RobinCaroff** [comment]
Here is the curl: 
```
curl 'https://graphql-dot-confetti-349319.uw.r.appspot.com/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: https://graphql-dot-confetti-349319.uw.r.appspot.com' --data-binary '{"query":"# Write your query or mutation here\nquery GeSpeakers {\n     sessions(first: 100) {\n        nodes {\n            title\n        }\n    }\n}"}' --compressed
```

**Comment by martinbonnin** [comment]
Very sorry about that, this was due to not completely populating the conference name (which is a new field in the config). See https://github.com/joreilly/Confetti/pull/120 for more details.
It should all be back to normal now

**Comment by RobinCaroff** [comment]
All good. Thanks @martinbonnin for the fix and thanks @sadstag for the bug report.
